services:
  db:
    image: postgres:18.2-alpine3.23
    container_name: mylibrary-db
    environment:
      POSTGRES_DB: mylibrarydb
      POSTGRES_USER: mylibrary
      POSTGRES_PASSWORD: mylibrary
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: mylibrary-api:latest
    container_name: mylibrary-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mylibrarydb
      SPRING_DATASOURCE_USERNAME: mylibrary
      SPRING_DATASOURCE_PASSWORD: mylibrary
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate

volumes:
  pgdata:
    name: mylibrary_pgdata